# Generated by Django 5.1 on 2024-09-02 01:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_date_alter_article_edited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='edited',
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(default=datetime.date(2024, 9, 1)),
        ),
    ]
